-- CREATE DATABASE exercice_01;

CREATE SCHEMA IF NOT EXISTS exercice_01;

SET search_path TO exercice_01;

CREATE TABLE IF NOT EXISTS personne (
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	prenom VARCHAR(50) NOT NULL,
	nom VARCHAR(50) NOT NULL,
	email VARCHAR(50) NOT NULL,
	telephone VARCHAR(50) NOT NULL
);