volumes:
  local_pgdata:
  pgadmin_data:


services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - local_pgdata:/var/lib/postgres/data

  pgadmin:
    depends_on:
      - db
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin_data:/var/libn/pgadmin

networks:
  postgres-pgadmin: