services:
  redis:
    image: redis:5.0-alpine3.10
    networks:
      - redis-network

  db:
    image: postgres:9.4
    volumes:
      - "data-postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - postgres-network

  vote:
    build: ./vote
    ports:
      - 8080:80
    depends_on:
      - redis
    networks:
      - redis-network
  
  result:
    build: ./result
    ports:
      - 4000:4000
    depends_on:
      - db
    networks:
      - postgres-network

  worker:
    build: ./worker
    networks:
      - postgres-network
      - redis-network

volumes:
  data-postgres:

networks:
  postgres-network:
  redis-network:
