name: docker push
on: push

jobs:
  build_and_push:
    strategy:
      matrix:
        app: [result, vote, worker]
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: login docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: build
        run: docker build -t ${{ secrets.DOCKERHUB_USER }}/${{ matrix.app }} ./${{ matrix.app }}

      - name: push
        run: docker push ${{ secrets.DOCKERHUB_USER }}/${{ matrix.app }}