name: Workflow lors d'un push
on: push
jobs:
  mon_job:
    runs-on: ubuntu-latest
    steps: 
      - name: Récupération de notre application
        uses: actions/checkout@v4

      - name: Mise en cache des dépendances
        uses: actions/cache@v4
        id: cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-package-${{ hashFiles('**/package-lock.json') }}

      - name: Installation des dépendances
        # if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: npm install

      - name: build de l'application
        # if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: npm run build

      # - name: Récupération de l'artéfact
      #   if: ${{ steps.cache.outputs.cache-hit == 'true' }}
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: mon_app
      
      - name: test
        run: npm run test
        continue-on-error: true

      - name: Upload du build de notre application
        if: ${{ success() && github.ref == 'refs/heads/main' }}
        uses: actions/upload-artifact@v4
        with:
          name: mon_app
          path: build

  download:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: mon_job
    steps:
      - name: Récupération de l'artéfact
        uses: actions/download-artifact@v4
        with:
          name: mon_app
