services:
  db:
    image: postgres

    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data


  backend:
    depends_on:
      - db
    build: ./backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mypassword
    ports:
      - "8080:8080"

  frontend:
    depends_on:
      - backend
    build: ./frontend
    ports:
      - "8081:8080"

volumes:
  postgres_data: