
services:
  db:
    image: mysql

    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: default
    
    restart: always

    volumes:
      - db_data:/var/lib/mysql

    ports:
      - 3306:3306

    networks:
      - mysql-phpmyadmin

  phpmyadmin:
    depends_on:
      - db

    image: phpmyadmin

    restart: always

    environment:
      PMA_HOST: db

    ports:
      - "8080:80"
    networks:
      - mysql-phpmyadmin

volumes:
  db_data:

networks:
  mysql-phpmyadmin:

# Commande docker pour démarrer les conteneurs en arrière-plan
# docker-compose up -d